### ISSUE TITLE
Incorrectly assumes proxyfmu.exe in working directory

### ISSUE THREAD

**Issue by ljamt** [open-simulation-platform/proxy-fmu#40]
Currently the working directory must be equal to location of proxyfmu.exe. Running libcosim should know where to find proxyfmu. 

Works:
`C:\osp\cosim\bin> .\cosim.exe run C:\path\to\config\`

Fails:
`C:\osp\cosim> .\bin\cosim.exe run C:\path\to\config\`

**Comment by markaren** [comment]
Possible solution: https://www.boost.org/doc/libs/1_77_0/doc/html/boost/dll/program_location.html

**Comment by markaren** [comment]
```cpp
 if (!proxyfmu::filesystem::exists(executable)) {
        boost::dll::fs::error_code ec;
        boost::dll::fs::path loc = boost::dll::program_location(ec);
        if (!ec.failed()) {
            executable = loc.parent_path().string() / executable;
        }
    }
```

Should work.
