### ISSUE TITLE
error: No resolvers available to handle URI: proxyfmu:xxxxx

### ISSUE THREAD

**Issue by vegetableno1** [open-simulation-platform/proxy-fmu#95]
Very appreciate your excellent work! 

After start cosim cli in terminal, I got error like this: **error: No resolvers available to handle URI: proxyfmu://127.0.0.1:9090?file=../DPController.fmu**. 
When I use distribued Co-simulation part, I can't find where to start the `proxyfmu_booter`. I can't find this executable file in proxy-fmu/cosim-cli/cosim app demo or anywhere, can anyone help me solve this problem?

**Comment by markaren** [comment]
Hi, if the idea is to run the model in a separate processor localhost, do this:

```
cosim run-single "proxyfmu://localhost?file=MyModel.fmu"
```

That should work, and `proxyfmu_booter` is not needed.

I see, however, that this executable is not shipped with cosim cli 0.7.1, but you could fetch it from 0.7.0 release if you need it (to host the model on a different location than localhost).

However, the error you get suggest that cosim cli is built without proxyfmu support. I tested the release of cosim CLI 0.7.1 just now, and that worked.

**Comment by vegetableno1** [comment]
Thank you for your help. With your assistance, I have successfully run cosim CLI 0.7.0 release. However, I have encountered another issue now. I want to try using distributed devices for co-simulation. 
## Scenario: 
One host and one laptop, with the host connected via Ethernet and the laptop via WiFi. Their IP addresses in the local network are 192.168.2.243 and 192.168.2.185 respectively. After disabling the firewall, they can ping each other.
Both devices have started the proxyfmu_booter (obtained from cosim 0.7.0), using the dp ship example（in demo cases master）, and configured OspStructureStructure.xml. NLPobserver.fmu is obtained from 192.168.2.185.
 `<Simulator name="Observer" source="proxyfmu://192.168.2.185:1234?file=file:///C:\Users\vone\Downloads\demo-cases-master\dp-ship\NLPobserver.fmu"/>`
## Running 
in the terminal of 192.168.2.243
```
.\cosim.exe run C:\Users\Administrator\Downloads\cosim_file\dp-ship\proxyfmu\OspSystemStructure.xml --output-dir=../output -v
```
## Error
encountered problems on 192.168.2.243.
```
error: Bad file: No such file: C:\Users\vone\Downloads\demo-cases-master\dp-ship\NLPobserver.fmu
```

**Comment by markaren** [comment]
If I remember correctly, `NLPobserver.fmu` needs to be located on the other computer (with the booter). You likely also need to use a relative path for the name. So try placing the FMU together with the booter.

```
<Simulator name="Observer" source="proxyfmu://192.168.2.185:1234?file=NLPobserver.fmu"/>
```

**Comment by vegetableno1** [comment]
Thank you! I have followed your suggestion, but here is the problem i have occured:
I copied the files needed to D:, and run cosim.
192.168.2.243
![image](https://github.com/open-simulation-platform/proxy-fmu/assets/69948267/a1fb5124-3576-40c4-b821-c2189a78d461)
192.168.2.185
![image](https://github.com/open-simulation-platform/proxy-fmu/assets/69948267/9a889916-a5b3-4a12-bb75-4a43878e69e2)
At the same time, I can run other `localhost` test cases on two different computers, proving that there is no issue with cosim cli and proxyfmu. How can I solve this distributed co-simulation problem?

**Comment by markaren** [comment]
Ok, it's been a long time since I worked on this. It seems I was wrong. The FMU needs to be located on the PC that runs the CLI. It is then transmitted to the booter application.

And answer your initial question regarding the booter. The anser is that the booter no longer exists. `proxyfmu` is the only executable needed. To use it as a remote host, use the command:

```
proxyfmu boot --port<port>
```

**Comment by vegetableno1** [comment]
Thank you! Have solved the problem with your help, now I can run Cosimulation distributedly^ ^
